### ISSUE TITLE
Implement Page Object Structure and Serialization

### ISSUE THREAD

**Issue by kfejzic** [pediferrous/pediferrous#8]
Develop the Page Object structure, including necessary attributes like MediaBox, Resources, and Contents. Implement serialization to represent pages accurately in the PDF.

**Comment by nfejzic** [comment]
This issue is related to #7, as per the specification, section 7.7.3.3 (page 104):

> The leaves of the page tree are page objects, each of which is a dictionary specifying the attributes of a
single page of the document.

See the specification for all entires in a page object. For now, we should focus only on the required entries: 

* Type - in our case always `Page`
* Parent - The page tree node that is the immediate parent of this page object
* Resources - A dictionary containing any resources required by the page contents. If the page requires no resources, the value of this entry shall be an empty dictionary.
* MediaBox - A rectangle, expressed in default user space units, that shall define the boundaries of the page.
