### ISSUE TITLE
Implement Cross-Reference Table Generation

### ISSUE THREAD

**Issue by kfejzic** [pediferrous/pediferrous#9]
Implement logic to generate the Cross-Reference Table, which maps object numbers to byte offsets in the file. This includes tracking object positions during serialization.

**Comment by nfejzic** [comment]
See PDF Specification (ISO 32000-2), section 7.5.4 (page 55): 

> The cross-reference table contains information that permits random access to indirect objects within
the PDF file so that the entire PDF file need not be read to locate any particular object.

According to the spec., cross-reference table might have multiple sections, with sections being added for incremental update of PDF. This is more relevant for PDF editors, not so much for our implementation and can be ignored for now. 

## Format summary: 

The table begins with keyword `xref` and ends with keyword `trailer`.
After `xref` one subsection is encoded. Subsection starts with two integers separated by whitespace, where first integer corresponds to the object number of first object in this subsection, and second number corresponds to the total number of objects in the subsection.
Following this are cross-ref. entries, one per line, each being **exactly 20 bytes long**.
Entries can be for used and deleted objects, denoted with `n` and `f` respectively. In our case, we should only generate used objects, so we should always use `n`.
The format of an entry is the following: 

```pdf
nnnnnnnnnn ggggg n eol
```

With `nnnnnnnnnn` being the 10-digit byte offset in the document for the object, `ggggg` is 5-digit generation number of the object, `n` marks that it's used. Numbers shall be padded with 0 if necessary.

**Comment by nfejzic** [comment]
Note: There's a newer approach with cross-reference streams. However, that seems a little more complicated and combines the cross-reference table and trailer in one. Since PDF is backwards compatible with old-style cross-reference tables, we should for now implement that. Cross-ref streams are a nice-to-have that can be implemented at a later point in time.

**Comment by kfejzic** [comment]
> See PDF Specification (ISO 32000-2), section 7.5.4 (page 55):
> 
> > The cross-reference table contains information that permits random access to indirect objects within
> > the PDF file so that the entire PDF file need not be read to locate any particular object.
> 
> According to the spec., cross-reference table might have multiple sections, with sections being added for incremental update of PDF. This is more relevant for PDF editors, not so much for our implementation and can be ignored for now.
> 
> ## Format summary:
> The table begins with keyword `xref` and ends with keyword `trailer`. After `xref` one subsection is encoded. Subsection starts with two integers separated by whitespace, where first integer corresponds to the object number of first object in this subsection, and second number corresponds to the total number of objects in the subsection. Following this are cross-ref. entries, one per line, each being **exactly 20 bytes long**. Entries can be for used and deleted objects, denoted with `n` and `f` respectively. In our case, we should only generate used objects, so we should always use `n`. The format of an entry is the following:
> 
> ```
> nnnnnnnnnn ggggg n eol
> ```
> 
> With `nnnnnnnnnn` being the 10-digit byte offset in the document for the object, `ggggg` is 5-digit generation number of the object, `n` marks that it's used. Numbers shall be padded with 0 if necessary.

Additionally to this, the generation number `ggggg` will in our case usually be `00000`, which represents new objects.
